### ISSUE TITLE
Faire pointer vers les nouveaux GeoServers

### ISSUE THREAD

**Issue by vstreignard** [CIRB/cirb.novac#2]
**Fichiers à modifier**
cirb/novac/tests/test_public_view.py

```
GEOSERVER_STA="http://geoserver.gis.irisnetlab.be"
GEOSERVER_PROD="http://geoserver.gis.irisnet.be"
PUBLIC_IDS="/geoserver/nova/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=nova:NOVA_DOSSIERS&maxFeatures=%s&outputFormat=json" % (str(NUMBER))
```

cirb/novac/browser/happy.py 

```
GEOSERVER_STA="http://geoserver.gis.irisnetlab.be"
GEOSERVER_PROD="http://geoserver.gis.irisnet.be"
PUBLIC_IDS="/geoserver/nova/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=nova:NOVA_DOSSIERS&maxFeatures=%s&outputFormat=json" % (str(NUMBER))
```

cirb/novac/browser/scripts/novac.js 
! Vérifier que les URLs calculées sont correctes
cirb/novac/browser/scripts/map.js 
! Vérifier que les URLs calculées sont correctes

**1. Fond de plan**
URLs:
http://geoservices-urbis.irisnetlab.be/geoserver/
http://geoservices-urbis.irisnet.be/geoserver/

Couches:
    urbisFR
    urbisNL

**2. Dossiers**
http://geoservices-others.irisnetlab.be/geoserver/Nova/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=Nova:Dossiers&maxFeatures=50&outputFormat=GML2
http://geoservices-others.irisnet.be/geoserver/Nova/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=Nova:Dossiers&maxFeatures=50&outputFormat=GML2

**Comment by laulaz** [comment]
Les adaptations sont passées en production avec succès aujourd'hui.
Je ferme donc cette issue.
